<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_No Of Employees_a-hfmk00q9k8t6</name>
   <tag></tag>
   <elementGuidId>52a40693-05bb-4767-9966-8789e0c13370</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;a-hfmk00q9k8t6&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='a-hfmk00q9k8t6']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[name=&quot;a-hfmk00q9k8t6&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>98d7a113-76e3-4ce4-b4e5-1d007a99a265</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>reCAPTCHA</value>
      <webElementGuid>1796ef61-6878-46de-9c53-3f2fc0b1577d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>304</value>
      <webElementGuid>a505626c-b412-4345-840a-578466f7da7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>78</value>
      <webElementGuid>42070767-8304-46ab-ab8b-1a547424049e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>5c2ce466-072d-4cad-af75-f09df99d92e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>a-hfmk00q9k8t6</value>
      <webElementGuid>a29e6d43-4a22-4582-ad8b-573ffb9a01f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>6b50345b-5376-4aa6-a084-f617eb029317</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>04f2ea13-cf46-42e9-ab37-78d3bb515929</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-forms allow-popups allow-same-origin allow-scripts allow-top-navigation allow-modals allow-popups-to-escape-sandbox allow-storage-access-by-user-activation</value>
      <webElementGuid>64a32d96-ab61-4ff0-9de2-3ae3d52d7cb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6Ld_-LcqAAAAAPbS9l-LgseMiB-svnHzxIiqfF5h&amp;co=aHR0cHM6Ly93d3cub3JhbmdlaHJtLmNvbTo0NDM.&amp;hl=en&amp;type=image&amp;v=ngcIAHyEnHQZZIKkyKneDTW3&amp;theme=light&amp;size=normal&amp;badge=bottomright&amp;anchor-ms=20000&amp;execute-ms=15000&amp;cb=d75bepv3gk51</value>
      <webElementGuid>a2f33f72-8954-491f-b874-2c7851550645</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-lf-yt-playback-inspected-xbp1oaewrnz7edvj</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>48164909-a4bc-4f12-98b1-a317ad233447</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-lf-vimeo-playback-inspected-xbp1oaewrnz7edvj</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3635aacc-ab52-4c1c-8cba-fd8a8403e015</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Nocaptcha-Form_getForm_Captcha&quot;)/div[1]/div[1]/iframe[1]</value>
      <webElementGuid>13b47b35-27b2-44fc-8325-bc65d5389e51</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='a-hfmk00q9k8t6']</value>
      <webElementGuid>f6250807-5a01-4522-b005-59dfe0f785fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Nocaptcha-Form_getForm_Captcha']/div/div/iframe</value>
      <webElementGuid>d4fef895-fe3e-44da-9ca5-fca441c5b8eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>3937f680-2a60-4177-a190-65f5e33ded8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'reCAPTCHA' and @name = 'a-hfmk00q9k8t6' and @src = 'https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6Ld_-LcqAAAAAPbS9l-LgseMiB-svnHzxIiqfF5h&amp;co=aHR0cHM6Ly93d3cub3JhbmdlaHJtLmNvbTo0NDM.&amp;hl=en&amp;type=image&amp;v=ngcIAHyEnHQZZIKkyKneDTW3&amp;theme=light&amp;size=normal&amp;badge=bottomright&amp;anchor-ms=20000&amp;execute-ms=15000&amp;cb=d75bepv3gk51']</value>
      <webElementGuid>47baffa1-2c00-4e17-ad63-947ba97bd369</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
