<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_No Of Employees_a-ya9wnmwaphkt</name>
   <tag></tag>
   <elementGuidId>2ebbd9cc-6b70-402e-a403-600df51ffc26</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;a-ya9wnmwaphkt&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='a-ya9wnmwaphkt']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[name=&quot;a-ya9wnmwaphkt&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>a20e9174-9999-472a-bb48-103ee46aa4b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>reCAPTCHA</value>
      <webElementGuid>3dcb730f-d477-4caf-8e72-27866fb64470</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>304</value>
      <webElementGuid>9a6a021c-01a3-49a0-85c1-ae3c8aba9d23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>78</value>
      <webElementGuid>83bc6117-aeed-4095-8966-e48832d4fee1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>bac41cf0-8e57-4703-8fa0-95c5ea347ba6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>a-ya9wnmwaphkt</value>
      <webElementGuid>6f68e109-bcbe-44ba-9162-a43d90086530</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>c19347de-db53-4e3d-acd4-bd26d49f9eb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>a63ec0f7-5c57-4518-809d-17de50b000e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-forms allow-popups allow-same-origin allow-scripts allow-top-navigation allow-modals allow-popups-to-escape-sandbox allow-storage-access-by-user-activation</value>
      <webElementGuid>71f54547-e76e-437d-a0c5-964ba0906cc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6Ld_-LcqAAAAAPbS9l-LgseMiB-svnHzxIiqfF5h&amp;co=aHR0cHM6Ly93d3cub3JhbmdlaHJtLmNvbTo0NDM.&amp;hl=en&amp;type=image&amp;v=ngcIAHyEnHQZZIKkyKneDTW3&amp;theme=light&amp;size=normal&amp;badge=bottomright&amp;anchor-ms=20000&amp;execute-ms=15000&amp;cb=pjvnllk7jzyn</value>
      <webElementGuid>bfdf3604-7d81-42c5-8c7a-586b2d8489ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-lf-yt-playback-inspected-xbp1oaewrnz7edvj</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4b5967ac-e97b-44fd-a16b-d7a23397848a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-lf-vimeo-playback-inspected-xbp1oaewrnz7edvj</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>841b5f6a-a568-49c2-af10-3d7a4eeab9c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Nocaptcha-Form_getForm_Captcha&quot;)/div[1]/div[1]/iframe[1]</value>
      <webElementGuid>2a99f61e-2a13-44cc-a423-b9aa01cf8fc5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='a-ya9wnmwaphkt']</value>
      <webElementGuid>ccd6b287-2482-44a8-a518-acca5200af59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Nocaptcha-Form_getForm_Captcha']/div/div/iframe</value>
      <webElementGuid>8d57307b-ae9a-4c19-a43f-2a2a90d845d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>368f56a2-fb6a-4e6e-8cce-5344cb600d08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'reCAPTCHA' and @name = 'a-ya9wnmwaphkt' and @src = 'https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6Ld_-LcqAAAAAPbS9l-LgseMiB-svnHzxIiqfF5h&amp;co=aHR0cHM6Ly93d3cub3JhbmdlaHJtLmNvbTo0NDM.&amp;hl=en&amp;type=image&amp;v=ngcIAHyEnHQZZIKkyKneDTW3&amp;theme=light&amp;size=normal&amp;badge=bottomright&amp;anchor-ms=20000&amp;execute-ms=15000&amp;cb=pjvnllk7jzyn']</value>
      <webElementGuid>6f3f01bb-7e56-4e25-b2ce-9ac14992fe59</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
