<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Full Name_FullName</name>
   <tag></tag>
   <elementGuidId>50d81c9d-b123-4cea-b483-f27a6be8caf3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Form_getForm_FullName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Form_getForm_FullName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Your Full Name*&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a686b270-3810-4eb0-b0a1-bd647c3d0731</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0706a4d5-cf6a-4897-8b0b-41c38de39e4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>FullName</value>
      <webElementGuid>a4639e83-5c07-44aa-98dc-6a9536f90bb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0faa849f-57b6-466f-9beb-bc08e02bc821</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Form_getForm_FullName</value>
      <webElementGuid>5605f360-7fd4-4e2b-85b5-7e87564c5270</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>7305b479-d898-40dd-a00e-2b90c11b2f1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Your Full Name*</value>
      <webElementGuid>9c64c985-77bc-4020-a4a9-218c7d0fb88a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Form_getForm_FullName&quot;)</value>
      <webElementGuid>a8c8340e-d1de-4e17-a88b-89cbfccd4fa8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Form_getForm_FullName']</value>
      <webElementGuid>8b0a8bec-3aa2-41f1-85dd-398f1068f12a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Form_getForm_FullName_Holder']/div/input</value>
      <webElementGuid>81db489a-042a-4afe-8c2b-842fd6a20ee7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>77dc41ea-dc3f-4d9f-8c7a-840f4f7221e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'FullName' and @id = 'Form_getForm_FullName' and @placeholder = 'Your Full Name*']</value>
      <webElementGuid>268fb8ad-3de4-426d-8ab5-85ce25bc56e1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
